version: "3.8"

services:

  nginx:
    image: nginx:alpine
    # container_name: nginx1:latest
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf

  service1:
    container_name: service1
    image: service1:latest
    build: ./frontend
    ports:
      - target: 5000
        published: 5000
        # environment:
        #   DATABASE_URI: ${DATABASE_URI}
    # deploy:
    #   replicas: 3

  service2:
    container_name: service2-api
    image: service2:latest
    build: ./service2-api
    ports:
      - target: 5001
        published: 5001
    # deploy:
    #   replicas: 3

  service3:
    container_name: service3-api
    image: service3:latest
    build: ./service3-api
    ports:
      - target: 5002
        published: 5002
    # deploy:
    #   replicas: 3

  service4:
    container_name: service4-api
    image: service4:latest
    build: ./service4-api
    ports:
      - target: 5003
        published: 5003
    # deploy:
    #   replicas: 3
  