version: "3.8"
services:
    database:
    container_name: database
    image: agray998/name-api:latest
    build: ./database
    deploy:
      replicas: 3
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
  service1:
    container_name: service1
    image: agray998/front-end:latest
    build: ./service1
    # environment:
    #   PASSWORD: ${MYSQL_ROOT_PASSWORD}
  service2:
    container_name: service2
    image: agray998/name-api:latest
    build: ./service2
    deploy:
      replicas: 3
  service3:
    container_name: service3
    image: agray998/unit-api:latest
    build: ./service3
    deploy:
      replicas: 3
  service4:
    container_name: service4
    image: agray998/effect-api:latest
    build: ./service4
    deploy:
      replicas: 3
  